version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-free
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=test
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/u01/app/oracle
    restart: always
    networks:
      - app-network

  spring-app:
    image: hamzakharbouch/tickets-spring-app:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=test
    depends_on:
      - oracle-db
    restart: always
    networks:
      - app-network

volumes:
  oracle-data:

networks:
  app-network:
    driver: bridge
    name: tickets_network